version: "3.9"

services:
  providergateway:
    image: massoft/provider-gateway:latest
    restart: always
    volumes:
      - ./config:/root/config
    env_file:
      - .env
    networks:
      - back-tier

  auth:
    image: massoft/go-oauth:latest
    restart: always
    volumes:
      - ./config:/root/config
    env_file:
      - .env
    networks:
      - back-tier

  cashbox:
    image: massoft/go-cashbox:latest
    restart: always
    volumes:
      - ./config:/root/config
    env_file:
      - .env
    networks:
      - back-tier

  paymentgateway:
    image: massoft/payment-gateway:latest
    restart: always
    volumes:
      - ./config:/root/config
    env_file:
      - .env
    networks:
      - back-tier

  mobile:
    image: massoft/mobile-service:latest
    restart: always
    volumes:
      - ./config:/root/config
    env_file:
      - .env
    networks:
      - front-tier
      - back-tier

  gateway:
    image: massoft/grpc-gateway:latest
    restart: always
    environment:
      CONFIG_PATH: '${GATEWAY_CONFIG_PATH}'
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    networks:
      - front-tier
      - back-tier
    ports:
      - "7000:7000"

  bpm:
    image: massoft/applications-service:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    networks:
      - back-tier

  bpmclient:
    image: massoft/mas-bpm-client:latest
    restart: always
    ports:
      - "1080:1080"
      - "10443:10443"
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    env_file:
      - .env
    networks:
      - front-tier

  portlclient:
    image: massoft/bpm-portal:latest
    restart: always
    ports:
      - "1081:1080"
      - "10444:10443"
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    env_file:
      - .env
    networks:
      - front-tier

  portadminlclient:
    image: massoft/bpm-portal_admin:latest
    restart: always
    ports:
      - "1082:1080"
      - "10445:10443"
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    env_file:
      - .env
    networks:
      - front-tier

  bpmdb:
    image: massoft/bpm-db:latest
    restart: always
    extra_hosts:
      - "myserver:192.168.1.10"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
