version: "3.9"
x-var: &HOST 172.20.10.2
services:
  providergateway:
    image: massoft/provider-gateway:latest
    container_name: "providergateway"
    restart: always
    volumes:
      - ./config:/root/config
    environment:
      - CONFIG_PATH=config/config.yaml

  auth:
    image: massoft/go-oauth:latest
    container_name: "auth"
    restart: always
    volumes:
      - ./config:/root/config
    environment:
      - CONFIG_PATH=config/config.yaml

  cashbox:
    image: massoft/go-cashbox:latest
    container_name: "cashbox"
    restart: always
    volumes:
      - ./config:/root/config
    environment:
      - CONFIG_PATH=config/config.yaml

  paymentgateway:
    image: massoft/payment-gateway:latest
    container_name: "paymentgateway"
    restart: always
    volumes:
      - ./config:/root/config
    environment:
      - CONFIG_PATH=config/config.yaml

  mobile:
    image: massoft/mobile-service:latest
    container_name: "mobile"
    restart: always
    volumes:
      - ./config:/root/config
    environment:
      - CONFIG_PATH=config/config.yaml

  gateway:
    image: massoft/grpc-gateway:latest
    container_name: "gateway"
    restart: always
    environment:
      - CONFIG_PATH=config/config.json
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs

  bpm:
    image: massoft/applications-service:latest
    container_name: "bpm"
    restart: always
    environment:
      - CONFIG_PATH=config/config.yaml
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs

  bpmclient:
    image: massoft/mas-bpm-client:latest
    container_name: "bpmclient"
    restart: always
    ports:
      - "1080:1080"
      - "10443:10443"
    volumes:
      - ./config:/root/config
      - ./certs:/root/certs
    environment:
      - CLIENT_gateway=http://gateway:7000

  bpmdb:
    image: massoft/bpm-db:latest
    container_name: "bpmdb"
    extra_hosts:
      - "myserver:192.168.1.10"
