version: "1.13"
x-var: &APP_DB
  server=host.docker.internal;user id=sa;password=hcs@mas;port=1433;database=GIZA;
services:
  gatway:
    image: massoft/masbillergateway:v1.0.1
    restart: always
    ports:
      - "7000:7000"
      - "8090:8090"
  biller:
    image: massoft/masbiller:v2.6.3
    restart: always
    environment:
      MAS_DB_CONNECTION: *APP_DB
      MAS_MAX_DB_CONNECTIONS: 100
      MAS_IDLE_DB_CONNECTION:  10
    ports:
      - "9002:9002"
  applications:
    image: massoft/applications:v2.0.29
    restart: always
    environment:
      MAS_DB_CONNECTION: *APP_DB
      MAS_MAX_DB_CONNECTIONS: 100
      MAS_IDLE_DB_CONNECTION:  10
    ports:
      - "9003:9003"
  maslogin:
    image: massoft/maslogin:v1.0.1
    restart: always
    environment:
      MAS_DB_CONNECTION: *APP_DB
      MAS_MAX_DB_CONNECTIONS: 100
      MAS_IDLE_DB_CONNECTION:  10
    ports:
      - "9001:9001"
  masquires:
    image: massoft/masqueries:v1.0.8
    restart: always
    environment:
      MAS_DB_CONNECTION: *APP_DB
      MAS_MAX_DB_CONNECTIONS: 100
      MAS_IDLE_DB_CONNECTION:  10
    ports:
      - "9004:9004"
  masclient:
    image: massoft/masclient:v1.0.16
    restart: always
    ports:
      - "25566:25566"
      - "9000:9000"
  mascustomers:
    image: massoft/customers:v1.0.0
    restart: always
    environment:
      MAS_DB_CONNECTION: *APP_DB
      MAS_MAX_DB_CONNECTIONS: 100
      MAS_IDLE_DB_CONNECTION:  10
    ports:
      - "9005:9005"