Env: dev
Version: 1
GatewayAddress: "gateway:7000"
ProjectTag: mas
MailServer:
  SMTP-Host: "smtp.gmail.com"
  SMTP-Port: 587
  Mail: ayoub.calls@gmail.com
  Password: JglgLIWYXq4iq0Y1iTXWiA==
  Enc: true

Connections:
- Name: NewMas
  Debug: true
  ServerIp: bpmdb
  DatabaseName: bpm
  DbPort: "1433"
  DbEngin: sqlserver
  UserName: Ngo=
  Password: CAppHIeKR6ph/w==
  Enc: true
  Type: Main
  MaxDbOpenConnections: 0
  MaxDbIdleConnections: 0

Services:
- ServiceName: ProviderGateway
  Connections:
    Mas: NewMas
  ApiAddress: :9008
  MetricsAdress: :8108

- ServiceName: ApplicationService
  Connections:
    Mas: NewMas
  ApiAddress: :9011
  MetricsAdress: :8011

- ServiceName: ActivityService
  Connections:
    Mas: NewMas
  ApiAddress: :9029
  MetricsAdress: :8029

- ServiceName: MobileService
  Connections:
    Mas: NewMas
  ApiAddress: :9016
  MetricsAdress: :8016

- ServiceName: GoAuth
  Connections:
    Mas: NewMas
  ApiAddress: :9009
  MetricsAdress: :8009

- ServiceName: AuthLogin
  Connections:
    Mas: NewMas
  ApiAddress: :9010
  MetricsAdress: :8010

- ServiceName: CashBox
  Connections:
    Mas: NewMas
  ApiAddress: :9018
  MetricsAdress: :9018

  
- ServiceName: paymentgateway
  Connections:
    Mas: NewMas
  ApiAddress: :9017
  MetricsAdress: :8017
  
  
- ServiceName: MobileService
  Connections:
    Mas: NewMas
  ApiAddress: :9016
  MetricsAdress: :8016


- ServiceName: NotificationsService
  Connections:
    Mas: NewMas
  ApiAddress: :9025
  MetricsAdress: :8025